### ISSUE TITLE
Can't use TICK_5

### ISSUE THREAD

**Issue by jplagostena** [slara/superslacker#16]
Hey guys,
I have a question regarding the TICK_5 events. 

As far as I can see the TICK_5 events are handled but discarded.

Is this an actual decision? Or is it just my problem because I can't see how can I change the self.eventname value (the default value for that is TICK_60, that's why TICK_5 are discarded, and it is set in the ProcessStateMonitor __init__ method)?

```python
    def handle_event(self, headers, payload):
        if headers['eventname'] in self.process_state_events:
            self.handle_process_state_change_event(headers, payload)
        elif headers['eventname'] == self.eventname:
            self.handle_tick_event(headers, payload)
```

Can you help me with this? 

Thanks in advance!

**Comment by AlekseiSaff** [comment]
with the latest merge it is available
