### ISSUE TITLE
pip installs an old version

### ISSUE THREAD

**Issue by ReeceM** [slara/superslacker#17]
Hi. This package works great, thank you. I noticed that there was a merge #15 that was added. 

When using pip install for superslacker on Ubuntu server 18.04 it installs version 0.3, but this version doesn’t have the updated dynamic attachments that were added 8 months ago to the package? 

Is there a reason for the package for being outdated on the pypi index?

Thanks
Reece

**Comment by cscetbon** [comment]
Hey @ReeceM, I met the same issue. I had to do 
`pip install -U git+https://github.com/slara/superslacker.git`

**Comment by ReeceM** [comment]
Hi @cscetbon, didn't know you could do that with pip 😅, should read more...

I ended up cloning the repo an installing it manually with `python setup.py`, so I guess that there are various ways around something. 

Thanks for sharing what you did, will be useful for future :).

**Comment by slara** [comment]
Hi, sorry for the late response. I updated the package in pypi.

**Comment by ReeceM** [comment]
Hi @slara, thats awesome, thank you very much.

The package is awesome 👍
