### ISSUE TITLE
[FATAL] Can't start 

### ISSUE THREAD

**Issue by OptimusKoala** [slara/superslacker#23]
I just have this

> r.create_from_cmd_line()
>   File "/usr/local/lib/python3.9/dist-packages/superslacker/superslacker.py", line 163, in create_from_cmd_line
>     return cls(**options.__dict__)
>   File "/usr/local/lib/python3.9/dist-packages/superslacker/superslacker.py", line 166, in __init__
>     ProcessStateMonitor.__init__(self, **kwargs)
>   File "/usr/local/lib/python3.9/dist-packages/superlance/process_state_monitor.py", line 36, in __init__
>     self.tickmins = self._get_tick_mins(self.eventname)
>   File "/usr/local/lib/python3.9/dist-packages/superlance/process_state_monitor.py", line 42, in _get_tick_mins
>     return float(self._get_tick_secs(eventname))/60.0
>   File "/usr/local/lib/python3.9/dist-packages/superlance/process_state_monitor.py", line 45, in _get_tick_secs
>     self._validate_tick_name(eventname)
>   File "/usr/local/lib/python3.9/dist-packages/superlance/process_state_monitor.py", line 49, in _validate_tick_name
>     if not eventname.startswith('TICK_'):
> AttributeError: 'NoneType' object has no attribute 'startswith'

Worked like a charm for month.

**Comment by AlekseiSaff** [comment]
please add 
--eventname=TICK_5 (or TICK_60) to the command line

**Comment by AlekseiSaff** [comment]
I've created PR to keep backward compatibility. Happy to see people are still using that product

**Comment by OptimusKoala** [comment]
Thank you very much, it's working perfectly. 
Thanks for your (very) quick responce :)
