### ISSUE TITLE
How to test it

### ISSUE THREAD

**Issue by nidhinpd** [slara/superslacker#5]
Is there any possible way to test the script?

**Comment by slara** [comment]
Hello @nidhinpd,

You can test it with `python setup.py test`. Tests can be added in `superslacker/tests/test_superslacker.py`

**Comment by nidhinpd** [comment]
Ok. But i am not asking about that testing.

```
[eventlistener:superslacker]
command=superslacker --token="mytesttoken" --channel="#supervisor" --hostname="LOCALHOST"
events=PROCESS_STATE,TICK_60,EVENT
```
This is how i configured it inside supervisord.conf
Then i restarted supervisor reread and updated and saw superslacker running. But i am not recieving any event update in my slack channel "supervisor"

i wrote a sample script that exits after runnng 1 minute. I ran it in supervisor. But when it exits after 1 min i got no notification about that on slack. Can u please clarify this issue. How can i make sure the slack is connected to superslack by manually sending some messages ?

**Comment by slara** [comment]
`superslacker` will alert on `'PROCESS_STATE_FATAL'` event. Your script needs to fail and enter FATAL state. Can you please verify your test script is not spawned after exit? Thanks

**Comment by nidhinpd** [comment]
events=PROCESS_STATE,TICK_60,EVENT
I also added EVENT in that. I thought that will notify any type state changes. Right ?

**Comment by slara** [comment]
Unfortunately we are limited to ' `PROCESS_STATE_FATAL' ` for now. I'm addressing this in #4. Sorry for this.
